services:
  minio:
    container_name: minio_storage
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  postgres:
    container_name: postgres_db
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: devstages_user
      POSTGRES_PASSWORD: devstages_pass
      POSTGRES_DB: dev_stages_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    container_name: adminer_ui
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  minio-data:
  postgres_data: